# 线上配置文件

server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.233.207.238:3306/richinterview
    username: richInterviewUser
    password: 5Fse3fNPkYFz6Bef
  # Redis 配置
  redis:
    database: 1
    host: 49.233.207.238
    port: 6379
    password: 123456
    timeout: 5000
  # Elasticsearch 配置
  # ES 对服务器内存要求较高，建议使用 8G 以上的服务器
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: RichInterview
    password: SwaggerDocs


# Nacos 配置中心，用于链接 nacos 服务
nacos:
  config:
    # nacos 地址
    server-addr: 49.233.207.238:8848
    bootstrap:
      # 开启预加载
      enable: true
    # 控制台 Data ID
    data-id: RichInterview
    # 控制台 Group Name
    group: RICH_INTERVIEW_GROUP
    # 选择的文件格式
    type: yaml
    # 开启自动刷新
    auto-refresh: true
